apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: rabbitmq-dynamic-secret-provider
  namespace: dapr-pub
spec:
  method: GET
  path: /rabbitmq/creds/dev
  provider:
    auth:
      kubernetes:
        mountPath: kubernetes
        role: rabbitmq
        serviceAccountRef:
          name: dapr-pub
          namespace: dapr-pub
    server: 'http://hashicorp-vault.hashicorp-vault.svc.cluster.local:8200'
    version: v2
  resultType: Data